services:
  - type: web
    name: gaming-hub-ultimate
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_OPTIONS
        value: "--max-old-space-size=384"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_SHARP_PATH
        value: "/opt/render/project/src/node_modules/sharp"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: NEXT_DISABLE_SOURCEMAPS
        value: "true"
      - key: NEXT_DISABLE_ESLINT
        value: "true"
      - key: NEXT_DISABLE_TYPE_CHECK
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    plan: free 