services:
  - type: web
    name: gaming-hub-ultimate
    env: node
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - next.config.mjs
        - tsconfig.json
        - tailwind.config.ts
        - postcss.config.mjs
        - app/**
        - components/**
        - lib/**
        - hooks/**
        - public/**
        - styles/** 