services:
  - type: web
    name: superhero-game
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1" 